### ISSUE TITLE
Different versions for 'stups-spring-oauth2-*' ?

### ISSUE THREAD

**Issue by jbellmann** [zalando-stups/logsink#3]
I have seen you have different versions for libs of 'stups-spring-oauth2-*' in your pom.xml. Do you have any issues when using same versions for both, because both were released together with same version?

BTW. Latest version is [1.0.15.RC1](https://github.com/zalando-stups/stups-spring-oauth2-support/releases/tag/1.0.15.RC1). Otherwise you could run into issues with response-status returned by PlanB-Provider.

@harti2006 could tell you more details here.

**Comment by ChristianLohmann** [comment]
It was copied by an existing project which was already in production. Thus ther should be no problems with these different versions. But i will bump the versions to the actual ones

**Comment by harti2006** [comment]
Yes, copy-pasta :laughing: 
There are also some dependencies which won't be needed. We will clean this up.
